// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'FooterStyle': string;
  'redStyle': string;
}
export const cssExports: CssExports;
export default cssExports;
