// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'decorateDiv': string;
  'selectListstyle': string;
  'sideHeaderStyle': string;
  'sideListStyle': string;
}
export const cssExports: CssExports;
export default cssExports;
