// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'articleDiv': string;
  'centerDiv': string;
  'pageDivTest': string;
  'pageTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
