// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centerDiv': string;
  'contactDivStyle': string;
  'contactLabelStyle': string;
  'contactPageStyle': string;
  'mailDivStyle': string;
  'mailInputStyle': string;
  'pageDivTest': string;
  'pageTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
