// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centerDiv': string;
  'decorateStyle': string;
  'enNameTitle': string;
  'nameTitle': string;
  'pageDivTest': string;
  'pageTitle': string;
  'posTitle': string;
  'profileRow': string;
  'selfieDivStyle': string;
}
export const cssExports: CssExports;
export default cssExports;
