// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centerDiv': string;
  'loadMoreButton': string;
  'pageDivTest': string;
  'pageTitle': string;
  'projectGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
