// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centerDiv': string;
  'circleLabel': string;
  'circleProgress': string;
  'developmentCol': string;
  'pageDivTest': string;
  'pageTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
