// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backGround': string;
  'backGroundIn': string;
  'centerDiv': string;
  'pageDivTest': string;
  'pageTitle': string;
  'testCode': string;
}
export const cssExports: CssExports;
export default cssExports;
