// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'GridStyle': string;
  'ListStyle': string;
  'testBar': string;
}
export const cssExports: CssExports;
export default cssExports;
