// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centerDiv': string;
  'headerBarStyle': string;
  'navStyle': string;
  'navXsStyle': string;
  'pageDivTest': string;
  'pageTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
